---
# tasks file for flowmaster-maven
- homebrew:
    name: maven
    state: present
  when: ansible_os_family == "Darwin"


- shell: sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
  become: yes
  when: ansible_os_family == "RedHat"
- shell: sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
  become: yes
  when: ansible_os_family == "RedHat"
- name: maven
  yum:
    name: "apache-maven"
    state: latest
  become: yes
  when: ansible_os_family == "RedHat"
