- hosts: flowmaster
  vars_prompt:
    - name: "spring_maven_sbt"
      prompt: "spring>(maven/sbt)?"
      default: "maven"
      private: no
    - name: "spring_packaging"
      prompt: "spring>(jar/war)?"
      default: "jar"
      private: no
    - name: "spring_packageName"
      prompt: "spring>Package Name?"
      default: "com.flowmaster"
      private: no
    - name: "spring_artifactId"
      prompt: "spring>Artifact Id?"
      default: "practice"
      private: no
    - name: "spring_version"
      prompt: "spring>Version?"
      default: "1.0.0-SNAPSHOT"
      private: no
    - name: "spring_dependecies_csv"
      prompt: "spring>Dependencies as csv?"
      default: "activemq,activiti-basic,actuator,actuator-docs,amqp,aop,artemis,batch,cache,camel,cloud-aws,cloud-aws-jdbc,cloud-aws-messaging,cloud-bus-amqp,cloud-bus-kafka,cloud-cloudfoundry-discovery,cloud-cluster-etcd,cloud-cluster-hazelcast,cloud-cluster-redis,cloud-cluster-zookeeper,cloud-config-client,cloud-config-server,cloud-connectors,cloud-contract-stub-runner,cloud-contract-verifier,cloud-contract-wiremock,cloud-dataflow-server-local,cloud-dataflow-shell,cloud-eureka,cloud-eureka-server,cloud-feign,cloud-hystrix,cloud-hystrix-dashboard,cloud-oauth2,cloud-ribbon,cloud-security,cloud-sleuth-stream,cloud-sleuth-zipkin-stream,cloud-starter,cloud-starter-consul-config,cloud-starter-consul-discovery,cloud-starter-sleuth,cloud-starter-zipkin,cloud-starter-zookeeper-config,cloud-starter-zookeeper-discovery,cloud-stream-binder-kafka,cloud-stream-binder-rabbit,cloud-task,cloud-turbine,cloud-turbine-stream,cloud-zuul,configuration-processor,data-cassandra,data-couchbase,data-elasticsearch,data-gemfire,data-jpa,data-jpa,data-mongodb,data-neo4j,data-redis,data-redis,data-rest,data-rest-hal,data-solr,derby,devtools,flyway,freemarker,groovy-templates,h2,hateoas,hsql,integration,jdbc,jersey,jooq,jta-atomikos,jta-bitronix,jta-narayana,liquibase,lombok,mail,mobile,mustache,mybatis,mysql,postgresql,ratpack,remote-shell,restdocs,retry,scs-circuit-breaker,scs-config-client,scs-service-registry,security,session,social-facebook,social-linkedin,social-twitter,thymeleaf,vaadin,validation,web,web-services,web-services,websocket,zipkin-server,zipkin-ui"
      private: no
  roles:
    - {role: flowmaster-build-spring-init}