---
# tasks file for flowmaster-java
- homebrew_cask:
    name: java
    state: present
  when: ansible_os_family == "Darwin"

- name: java
  yum:
    name: "java"
    state: latest
  become: yes
  when: ansible_os_family == "RedHat"
