---
# tasks file for flowmaster-docker-toolbox
- homebrew_cask:
    name: docker-toolbox
    state: present
  when: ansible_os_family == "Darwin"
- name: docker
  yum:
    name: "docker"
    state: latest
  become: yes
  when: ansible_os_family == "RedHat"
- pip:
    name: docker-py
    state: latest
  become: yes
  when: ansible_os_family == "RedHat"

