---
# tasks file for flowmaster-ansible
- yum:
    name: python-pip
    state: latest
  become: yes
- yum:
    name: python-setuptools
    state: latest
  become: yes
- easy_install:
    name: virtualenv
    state: latest
  become: yes
- easy_install:
    name: pip
    state: latest
- easy_install:
    name: virtualenv
    state: latest