---
# tasks file for flowmaster-ansible
- yum:
    name: python-pip
    state: latest
  become: yes
  when: ansible_os_family == "RedHat"
- yum:
    name: python-setuptools
    state: latest
  become: yes
  when: ansible_os_family == "RedHat"
- easy_install:
    name: virtualenv
    state: latest
  become: yes
  when: ansible_os_family == "RedHat"
- easy_install:
    name: pip
    state: latest
  when: ansible_os_family == "RedHat"
- easy_install:
    name: virtualenv
    state: latest
  when: ansible_os_family == "RedHat"