---
# tasks file for flowmaster-git
- homebrew:
    name: git
    state: present
  when: ansible_os_family == "Darwin"

- name: git
  yum:
    name: "git"
    state: latest
  become: yes
  when: ansible_os_family == "RedHat"
