---
# tasks file for flowmaster-docker-spring-springxd
- name: singlenode
  docker_image:
    name: springxd/singlenode
  become: yes

- name: shell
  docker_image:
    name: springxd/shell
  become: yes

- docker_container:
    name: singlenode
    state: started
    image: springxd/singlenode
    ports:
     - "9393:9393"
     - "9000:9000"
    exposed_ports:
      - 9393
      - 9000
    volumes: "/tmp/springxd/:/tmp/springxd/"
  become: yes