---
# tasks file for flowmaster-docker-nginx
- name: nginx
  docker_image:
    name: nginx
  become: yes

- docker_container:
    name: nginx
    state: present
    image: nginx
    command: service nginx start
    ports:
     - "80:80"
    exposed_ports:
      - 80
  become: yes