---
# tasks file for flowmaster-docker-nginx
- name: nginx
  docker_image:
    name: nginx
  become: yes

- docker_container:
    name: nginx
    state: present
    image: nginx:latest
    command: sleep infinity
    published_ports: "80:80"
  become: yes