---
# tasks file for flowmaster-docker-nginx
- name: nginx
  docker_image:
    name: nginx
  become: yes

- synchronize:
    src: "{{ role_path }}/files/"
    dest: "/tmp/html"

- docker_container:
    name: nginx
    state: started
    image: nginx
    ports:
     - "80:80"
    exposed_ports:
      - 80
    volumes: "/tmp/html/:/usr/share/nginx/html/"
  become: yes